# Generated by Django 4.1.3 on 2022-11-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmvt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='familia',
        ),
    ]
