# Generated by Django 4.1.3 on 2022-11-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmvt', '0002_rename_curso_familia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='camada',
            new_name='edad',
        ),
    ]
